# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: easyjs
shorttitle: Egg, 前端工程, 多端技术
subtitle: An easy suite of JavaScript framework and library designed for working with Egg,Vue,React,Webpack,Flutter
description: easyjs 专注 Egg, 前端工程, 多端技术等领域，涉及 Egg Vue SSR 服务端渲染,Egg React SSR 服务端渲染, Webpack 前端工程化，Serverless, Flutter等技术学习和实践。期望通过工程体系方式来实现整个大前端工程体系的建设, 让前端开发效率能够得到显著提升！
keywords: Egg,Eggjs,Vue SSR,React SSR,React 服务端渲染,Vue 服务端渲染,Vue Server-Side Rendering,React Server-Side Rendering,Server Side Rendering with React,Egg Vue SSR, Egg React SSR, Egg React Server Side Render(ssr), Egg Vue Server Side Render(ssr), egg-webpack, flutter android 混合构建, flutter ios 混合构建
author: sky
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://easyjs.cn
root: /
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing index.html from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
friend_dir: friends
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude:
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace:

prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'tomorrow'
  line_number: false    # default false
  custom_css:
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 120
  order_by: -createTime

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: easy-team

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/easy-team/easy-team.gitee.io.git
  branch: master
search:
  path: search.xml
  field: post
baidusitemap:
    path: baidusitemap.xml
sitemap:
    path: sitemap.xml
feed:
  type: atom
  path: atom.xml
  limit: 50
